name: Publish on GitHub pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Publish to GH pages
      run: |
        git checkout gh_pages
        mv dist/* .
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "ssr-blog+github-actions[bot]@users.noreply.github.com"
        
        git add --all
        git commit -m "Release $(date)"
        
        git push
